### ISSUE TITLE
【归档】项目实践中遇到的问题及暂行的解决办法（想起一点更一点）

### ISSUE THREAD

**Issue by shawxlee** [shawxlee/practice-works#1]
**问题：**
引入`vue-touch`组件后绑定了`swipeup`和`swipedown`事件，滑动就变得非常卡顿，并且在切换`tab-pane`或`v-if`后新页面滑动失效，但鼠标可以正常滚动，判断不是视图的bug

**分析：**
`vue-touch`官方向组件预设了CSS属性`touch-action: none;`，因此在应用组件之后，浏览器或系统默认的触摸操作全部被禁用了
> CSS属性 `touch-action` 用于指定某个给定的区域是否允许用户操作，以及如何响应用户操作（比如浏览器自带的划动、缩放等）。
> `none` —— 当触控事件发生在元素上时，不进行任何操作。

**解决：**（暂未引发其他问题）
```css
* {
    touch-action: auto !important;
}
```
> 初始值 `auto` —— 当触控事件发生在元素上时，由浏览器来决定进行哪些操作，比如对viewport进行平滑、缩放等。

**Comment by shawxlee** [comment]
**问题：**
`v-for`数据过滤：空格分隔搜索词，全文匹配所有包含至少一个关键词的项，实时显示搜索结果

**分析：**
`v-model`动态绑定输入文本， `split()`方法按空格分割为一个数组；提取用于匹配的item对象列表为一个数组，`replace()`方法清除数据中所有标点符号；嵌套for循环遍历两个数组，`includes()`方法检测数据文本中是否包含关键词，返回`filter()`方法的计算属性
> `split()` 方法用于把一个字符串分割成字符串数组。
> `replace()` 方法用于在字符串中用一些字符替换另一些字符，或替换一个与正则表达式匹配的子串。
> `includes()` 方法用来判断一个数组是否包含一个指定的值，如果是返回 true，否则false。
> `filter()` 方法创建一个新的数组，新数组中的元素是通过检查指定数组中符合条件的所有元素。

**解决：**
```html
<div v-for="item in filterData" :key="item.id">……</div>
```
```javascript
computed: {
    filterData () {
        var stArr = searchText.split(' '),
        itemKeys = [item.key1, item.key2, item.key3, item.key5, item.key7];

        return this.data.filter(function (item) {
            // 性能最好的循环方式
            var i, lenI, j, lenJ;
            for (i = 0, lenI = stArr.length; i < lenI; i++) {
               for (j = 0, lenJ = itemKeys.length; j < lenJ; j++) {
                   // 必须用if条件判断后返回true，循环中直接返回语句只会输出第一条return的结果
                   if (itemKeys[j].replace(/[ \/ ·，“”……：]+/g, '').toLowerCase().includes(stArr[i].toLowerCase())) {
                       return true;
                    }
                }
            }
        }
    }
}
```

**Comment by shawxlee** [comment]
**问题：**
data属性中声明好的空数组`dataArr: []`，初始运行`axios.get().then()`将取到的数据赋值给dataArr。但v-for列表渲染始终空白，在控制台可知请求成功并取到了数据，而dataArr依然为空

**分析：**
`then()`方法内部的`this`并非指向当前vue实例，需在外部声明后调用
> `then()` 方法返回一个  Promise 。它最多需要有两个参数：Promise 的成功和失败情况的回调函数。

**解决：**
```javascript
methods: {
    loadData () {
        var vm = this;
        axios.get('/data.json')
        .then(function (response) {
            vm.dataArr = response.data;
        })
        .catch(function (error) {
	    console.log(error);
	});
    }
}
```

**Comment by shawxlee** [comment]
**问题：**
input搜索框做了伸缩的过渡效果，希望每次展开时能自动获得焦点，并且点击末尾的按钮时input不失去焦点

**分析：**
向`<input>`标签添加它的`autofocus`属性可基本满足自动获得焦点的需求，但vue的官方文档说了：
> 注意：`autofocus` 在移动版 Safari 上不工作

并且给出了自定义指令v-focus的方法解决这个问题；同时，配合`<transition>`过渡方法使用的v-if顺便也实现了每次展开都重新渲染input以获得焦点的目的；
click动作的事件触发顺序依次为：`mousedown`→`mouseup`→`click`，点击input外部使其失去焦点的是`mousedown`这一步，阻止它的默认行为即可。

**解决：**
```html
<transition name="stretch">
    <input type="text" v-if="isStretch" v-model="searchText" v-focus>
</transition>
<button type="button" @mousedown.prevent @click="onSearch">清除</button>
```
```javascript
directives: {
    focus: {
        // 指令的定义
        inserted (el) {
            el.focus();
        }
    }
}
```

**Comment by shawxlee** [comment]
**问题：**
内联元素中的文本居中对齐的通用办法

**分析：**
贴一下之前学习CSS时利用[ProcessOn](https://www.processon.com/)自己绘制的行级盒子结构图：

![行级盒子结构分析@shawxlee绘制](https://github.com/shawxlee/study-notes/blob/master/md%E5%9B%BE%E7%89%87/%E8%A1%8C%E7%BA%A7%E7%9B%92%E5%AD%90%E7%BB%93%E6%9E%84%E5%88%86%E6%9E%90@shawxlee%E7%BB%98%E5%88%B6.png?raw=true)

水平居中很简单，一般`text-align: center;`就ok了；麻烦的是垂直居中，根据结构分析，垂直方向上没有精准的中线定义，所以`vertical-align`属性根本无法满足要求，于是最好自行配合调整4个属性：`font-size`、`line-height`、`padding-y`、`height`

**解决：**（暂未引发其他问题）
```css
/* 当font-size为基准值1rem时，line-height = height即可 */
.inline-el {
    width: 3rem;
    height: 5rem;
    font-size: 1rem;
    line-height: 5;
    text-align: center;
}

/* 当font-size非基准值时，设line-height = 1， paddingTop = paddingBottom = (height - fontSize) / 2 */
.inline-el {
    width: 3rem;
    height: 5rem;
    padding-top: 2.1rem;
    padding-bottom: 2.1rem;
    font-size: .8rem;
    line-height: 1;
    text-align: center;
}
```

**Comment by shawxlee** [comment]
**问题：**
引入[Bootstrap](https://getbootstrap.com/)后，利用网格系统布局非常方便，但一行仅能放置2或3的倍数，并且是在固定容器宽度后调整内容的尺寸，当我想放5个差不多宽的块，或者让后项根据前项的占比响应式填充剩余宽度，就不太方便了

**分析：**
网格系统适用于限定每项最大宽度或项目之间占比的情况，若要不受数量或容器宽度的限制，可使用Flex布局
> **Enable flex behaviors**: Apply `display` utilities to create a flexbox container and transform **direct children elements** into flex items. Flex containers and items are able to be modified further with additional flex properties.

**解决：**
```html
<!-- 根据内容尺寸自动调整每项宽度以填充行 -->
<div class="d-flex">
    <div class="flex-fill">Flex item with a lot of content</div>
    <div class="flex-fill">Flex item 2</div>
    <div class="flex-fill">Flex item 3</div>
</div>

<!-- 某块固定尺寸后，邻项响应式填充剩余宽度 -->
<div class="d-flex">
    <div style="width: 3rem;">Flex item 1</div>
    <div style="width: calc(100% - 3rem);">Flex item 2</div>
</div>

<!-- 允许项目总宽度溢出行 -->
<div class="d-flex flex-nowrap">
    ……
</div>
```

**Comment by shawxlee** [comment]
**问题：**
内容较多的文本不换行也不溢出，可在行内左右滑动查看

**分析：**
向该文本元素添加CSS属性`white-space: nowrap;`和`overflow-x: auto;`即可，但注意元素必须为块元素或行内块元素，需要设定好宽度

**解决：**
```css
p {
    width: 80%;
    white-space: nowrap;
    overflow-x: auto;
}
```

**Comment by shawxlee** [comment]
**问题：**
为配合移动端查看，在CSS文档的全局样式调整基准字号为12px，却发现在不同屏幕尺寸的设备上字号忽大忽小，完全未实现响应视图

**分析：**
针对这个问题在网上查了好一阵，然后看到了大佬的这篇文章：
> [移动端应该如何动态设置字体大小？ - web开发 - SegmentFault 思否](https://segmentfault.com/a/1190000004189237)

分析得非常详细和完善，最后也贴出了最优方法的源码，就不害臊地直接拿来用了~

**解决：**
```html
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
```
```javascript
// 利用js计算当前设备的DPR，动态设置html的font-size，利用css的选择器根据DPR来设置不同DPR下的字体大小
!function (win,lib) {
	var timer,
	doc = win.document,
	docElem = doc.documentElement,
	vpMeta = doc.querySelector('meta[name="viewport"]'),
	dpr = 0,
	scale = 0,
	flexible = lib.flexible || (lib.flexible = {});
	// 设置了 viewport meta
	if (vpMeta) {
		console.warn("将根据 meta 标签缩放比例调整基准字号");
		var initial = vpMeta.getAttribute("content").match(/initial\-scale=([\d\.]+)/);
		if (initial) {
				scale = parseFloat(initial[1]); // 已设置的 initialScale
				dpr = parseInt(1 / scale);      // 设备像素比 devicePixelRatio
			}
		}
		function setFontSize() {
			var winWidth = docElem.getBoundingClientRect().width;
			if (winWidth / dpr > 540) {
				(winWidth = 540 * dpr);
			}
		// 根节点 fontSize 根据宽度决定
		var baseSize = winWidth / 25;
		docElem.style.fontSize = baseSize + "px";
		flexible.rem = win.rem = baseSize;
	}
	// 调整窗口时重置
	win.addEventListener("resize", function() {
		clearTimeout(timer);
		timer = setTimeout(setFontSize, 300);
	}, false);
	// orientationchange 时也需要重算下
	win.addEventListener("orientationchange", function() {
		clearTimeout(timer);
		timer = setTimeout(setFontSize, 300);
	}, false);
	// pageshow
	// keyword: 倒退 缓存相关
	win.addEventListener("pageshow", function(e) {
		if (e.persisted) {
			clearTimeout(timer);
			timer = setTimeout(setFontSize, 300);
		}
	}, false);
	// 设置基准字体
	if ("complete" === doc.readyState) {
		doc.body.style.fontSize = 12 * dpr + "px";
	} else {
		doc.addEventListener("DOMContentLoaded", function() {
			doc.body.style.fontSize = 12 * dpr + "px";
		}, false);
	}
	setFontSize();
	flexible.dpr = win.dpr = dpr;
	flexible.refreshRem = setFontSize;
	flexible.rem2px = function(d) {
		var c = parseFloat(d) * this.rem;
		if ("string" == typeof d && d.match(/rem$/)) {
			c += "px";
		}
		return c;
	};
	flexible.px2rem = function(d) {
		var c = parseFloat(d) / this.rem;
		if ("string" == typeof d && d.match(/px$/)) {
			c += "rem";
		}
		return c;
	}
} (window, window.lib || (window.lib = {}));
```

**Comment by shawxlee** [comment]
**问题：**
如何消除Bootstrap组件中按钮等点击后的边框和阴影

**分析：**
官方预设点击事件或焦点事件等将依次切换focus及active的类/伪类样式，在私有样式中重新声明覆盖即可

**解决：**
```css
/* 折叠组件 */
.navbar-toggler:focus,
.navbar-toggler:active:focus,
.navbar-toggler:active.focus,
.navbar-toggler.active,
.navbar-toggler.active:focus,
.navbar-toggler.active.focus,
.navbar-toggler.focus {
    box-shadow: none;
    outline: none;
}
/* 按钮 */
.btn:focus,
.btn:active:focus,
.btn:active.focus,
.btn.active,
.btn.active:focus,
.btn.active.focus,
.btn.focus {
    box-shadow: none;
    outline: none;
}
/* 输入框 */
.form-control:focus,
.form-control:active:focus,
.form-control:active.focus,
.form-control.active,
.form-control.active:focus,
.form-control.active.focus,
.form-control.focus {
    box-shadow: none;
    outline: none;
}
```

**Comment by shawxlee** [comment]
**问题：**
发起ajax请求后，尝试再次请求无响应

**分析：**
因为数据url已经请求过了，结果已经缓存，不再重新执行请求，可以向url末尾添加时间戳或随机参数，相当于每次请求的不同的地址，但实际指向同一地址

**解决：**
```javascript
// 假设数据地址为https://github.com/shawxlee/practice-works/data.json
var url = 'https://github.com/shawxlee/practice-works/data.json?t=' + new Date().getTime();
```

**Comment by shawxlee** [comment]
**问题：**
希望当搜索框有内容时，input失去焦点后宽度缩短为文本长度，获得焦点后伸长为100%；需要绑定v-model中的变量，无法写在css文件中，同时要用focus事件布尔值切换开关，并且实现过渡效果

**分析：**
`v-bind`绑定内联样式，利用三元表达式切换样式的应用，css中添加`transition`过渡属性

**解决：**
```html
<input :style="[isFocus ? '' : {width: searchText.length + 3 + 'rem'}]" type="text" @focus="isFocus = true" @blur="isFocus = false" v-model="searchText">
```
```css
input {
    width: 100%;
    transition: width .1s linear;
}
```

**Comment by shawxlee** [comment]
**问题：**
点击不同按钮激活当前排序方式，在同一按钮上反复点击切换正序倒序，同时小图标应用对应的禁用样式

**分析：**
绑定点击事件切换`sortOrder`的值，`isReverse`取反切换正倒序，watch中监听`sortOrder`，一旦排序方式改变，即复位`isReverse`为`false`

**解决：**
```html
<button :class="{active: sortOrder == 1}" @click="onSort(1)">按年份排序 
    <span>
        <i class="fas fa-caret-left mr-0" :class="{disabled: !isReverse}"></i>
        <i class="fas fa-caret-right ml-0" :class="{disabled: isReverse}"></i>
    </span>
</button>
<button :class="{active: sortOrder == 2}" @click="onSort(2)">按评分排序 
    <span>
        <i class="fas fa-caret-left mr-0" :class="{disabled: !isReverse}"></i>
        <i class="fas fa-caret-right ml-0" :class="{disabled: isReverse}"></i>
    </span>
</button>

<button :class="{active: sortOrder == 3}" @click="onSort(3)">按更新排序 
    <span>
        <i class="fas fa-caret-left mr-0" :class="{disabled: !isReverse}"></i>
        <i class="fas fa-caret-right ml-0" :class="{disabled: isReverse}"></i>
    </span>
</button>
```
```javascript
data: {
    sortOrder: 1,
    isReverse: false
},
methods: {
    onSort (order) {
        this.sortOrder = order;
	this.isReverse = !this.isReverse;
    }
},
computed: {
    sortFilms () {
	var sortOrder = this.sortOrder,
	isReverse = this.isReverse;

	return this.films.sort(function (a, b) {
		if (sortOrder == 1) {
			return isReverse ? b.year - a.year : a.year - b.year;
		} else if (sortOrder == 2) {
			return isReverse ? a.score - b.score : b.score - a.score;
		} else {
			return isReverse ? a.id - b.id : b.id - a.id;
		}
	});
    }
},
watch: {
    sortOrder () {
	this.isReverse = false;
    }
}
```

**Comment by shawxlee** [comment]
**问题：**
对评分高低分7个级别显示不同颜色，if语句可以实现，但代码比较繁琐

**分析：**
评分为数字值，可以将颜色放入数组中，分数段作为数组中的索引，来返回颜色值

**解决：**
```html
<p :style="{'background-color': scoreColor(item)}">{{ item.score }}</p>
```
```javascript
methods: {
    scoreColor (item) {
        var colors = ['#cd0000', '#cd8500', '#cdcd00', '#00cd00', '#00cdcd', '#0000cd', '#912cee'],
	colorIndex = Math.floor(item.score) - 3;

        return colors[colorIndex];
    }
}
```
> `Math.floor()` 返回小于或等于一个给定数字的最大整数。

**Comment by shawxlee** [comment]
**问题：**
实现返回底部和直达底部的滚动效果

**分析：**
利用jquery中的`animate()` 方法结合`scrollTop`属性，实现滚动的动画效果
> `animate()` 方法执行 CSS 属性集的自定义动画。该方法通过CSS样式将元素从一个状态改变为另一个状态。CSS属性值是逐渐改变的，这样就可以创建动画效果。
> `Element.scrollTop` 属性可以获取或设置一个元素的内容垂直滚动的像素数。

**解决：**
```javascript
var toTop = $('#toTop'),
toBottom = $('#toBottom')；
// 回到顶部
toTop.on('click', function () {
    $('html, body').animate({ scrollTop: 0 }, 300, 'linear');
});
// 直达底部
toBottom.on('click', function () {
    var height = $(document).height();
    $('html, body').animate({ scrollTop: height }, 300, 'linear');
});
```

**Comment by shawxlee** [comment]
**问题：**
同一页面分为左右两块区域独立滚动，点击左侧导航定位到右侧内容，导航能随着内容滚动激活，并且希望锚点定位不被顶部导航栏遮挡

**分析：**
利用Bootstrap中的[Scrollspy组件](https://getbootstrap.com/docs/4.3/components/scrollspy/)实现滚动监听功能，使导航随着内容滚动激活，注意给关键元素们添加正确的定位，向导航元素添加`overflow-y: auto;`使之也可滚动。
计算顶部导航栏的遮挡高度，设置空锚点，利用`position: relative;`偏移锚点位置，使之定位到顶部时撑开一定高度使内容不被遮挡，并且不会影响视图间距。

**解决：**
```html
<body data-spy="scroll" data-target="#example-nav" data-offset="72">
    <!-- 顶部有固定导航栏，高度为72px -->
    ……
    <!-- 利用网格系统分左右两个区域 -->
    <div class="container">
        <div class="col-4">
            <!-- 导航区域 -->
            <div class="list-group" id="example-nav">
                <a class="list-group-item list-group-item-action" href="#item-1">item-1</a>
                <a class="list-group-item list-group-item-action" href="#item-2">item-2</a>
                ……
            </div>
        </div>
        <div class="col-8">
            <!-- 内容区域 -->
            <div class="example-content">
                <div class="example-content-item-1">
                    <!-- 给每个项目设置空锚点 -->
                    <div class="item-id" id="item-1"></div>
                    <div class="item-1-content">……</div>
                </div>
                <div class="example-content-item-2">
                    <div class="item-id" id="item-2"></div>
                    <div class="item-2-content">……</div>
                </div>
                ……
            </div>
        </div>
    </div>
</body>
```
```css
body {
	position: relative;    /* 给监听对象添加relative定位 */
}
.list-group {
	position: fixed;    /* 给导航元素添加fixed定位 */
	top: 72px;    /* 跨过顶部导航栏 */
	left: 0;
	height: calc(100vh - 72px);    /* 计算可见高度 */
	overflow-y: auto;    /* 添加y轴方向的滚动属性 */
}
.item-id {
	position: relative;    /* 给锚点元素添加relative定位 */
	top: -72px;    /* 上移锚点位置跨过顶部导航栏 */
}
```

**Comment by shawxlee** [comment]
**问题：**
一个v-for列表共有30个标签，初始时只显示前17个，第18个标签为“更多”按钮，点击后则显示所有标签，同时隐藏“更多”按钮

**分析：**
v-for结构中有两种方式可以实现，而若想代码最简洁，可以在v-for后搭配v-if，利用三元表达式有条件地渲染列表，但vue官方不建议这么做：
> 注意我们不推荐在同一元素上使用 v-if 和 v-for。更多细节可查阅[风格指南](https://cn.vuejs.org/v2/style-guide/#%E9%81%BF%E5%85%8D-v-if-%E5%92%8C-v-for-%E7%94%A8%E5%9C%A8%E4%B8%80%E8%B5%B7-%E5%BF%85%E8%A6%81)。
>>一般我们在两种常见的情况下会倾向于这样做：
>> * 为了过滤一个列表中的项目 (比如 v-for="user in users" v-if="user.isActive")。在这种情形下，请将 users 替换为一个计算属性 (比如 activeUsers)，让其返回过滤后的列表。
>> * 为了避免渲染本应该被隐藏的列表 (比如 v-for="user in users" v-if="shouldShowUsers")。这种情形下，请将 v-if 移动至容器元素上 (比如 ul, ol)。

这里我想实现的效果属于第一种情况，如果数据量较大，建议替换为计算属性，因为过滤更高效、渲染更高效、可维护性更强，不过我这个标签列表很小，想要代码最简洁，我觉得可以利用一下v-if

**解决：**
```html
<a class="btn" v-for="(item, index) in tags" v-if="moreHidden ? index < 17 : true">{{ item.tag }}</a>
<a class="btn more" v-if="moreHidden" @click="moreHidden = false">更多</a>
```
```javascript
data: {
    tags: [……],
    moreHidden: true
}
```

**Comment by shawxlee** [comment]
**问题：**
安卓系统下，`.list-group`组件添加`position: fixed;`定位后，子元素`.list-group-item`右侧1px的边框看不见了，修改`z-index`层级也无效

**分析：**
暂时未找到发生这个问题的根本原因，不过这里我只需要显示一个右边框出来，所以可以向外层容器添加右边框，同时将子元素的右边框删除或者隐藏，这里为了保留上下边框不能删除，所以采用隐藏的方式

**解决：**
```css
.list-group {
    position: fixed;
    width: 30%;
    overflow-x: hidden;
}
.list-group-item {
    width: calc(100% + 1px);
}
```
