### ISSUE TITLE
问题：如何消除Bootstrap组件中按钮等点击后的边框和阴影

### ISSUE THREAD

**Issue by shawxlee** [shawxlee/practice-works#10]
如何消除Bootstrap组件中按钮等点击后的边框和阴影

**Comment by shawxlee** [comment]
**分析：**
官方预设点击事件或焦点事件等将依次切换`focus`及`active`的类/伪类样式，在私有样式中重新声明覆盖即可

**解决：**
```css
/* 折叠组件 */
.navbar-toggler:focus,
.navbar-toggler:active:focus,
.navbar-toggler:active.focus,
.navbar-toggler.active,
.navbar-toggler.active:focus,
.navbar-toggler.active.focus,
.navbar-toggler.focus {
    box-shadow: none;
    outline: none;
}
/* 按钮 */
.btn:focus,
.btn:active:focus,
.btn:active.focus,
.btn.active,
.btn.active:focus,
.btn.active.focus,
.btn.focus {
    box-shadow: none;
    outline: none;
}
/* 输入框 */
.form-control:focus,
.form-control:active:focus,
.form-control:active.focus,
.form-control.active,
.form-control.active:focus,
.form-control.active.focus,
.form-control.focus {
    box-shadow: none;
    outline: none;
}
```
