### ISSUE TITLE
希望当搜索框有内容时，input失去焦点后宽度缩短为文本长度，获得焦点后伸长为100%；需要绑定v-model中的变量，无法写在css文件中，同时要用focus事件布尔值切换开关，并且实现过渡效果

### ISSUE THREAD

**Issue by shawxlee** [shawxlee/practice-works#12]
**问题：**
希望当搜索框有内容时，input失去焦点后宽度缩短为文本长度，获得焦点后伸长为100%；需要绑定v-model中的变量，无法写在css文件中，同时要用focus事件布尔值切换开关，并且实现过渡效果

**Comment by shawxlee** [comment]
**分析：**
`v-bind`绑定内联样式，利用三元表达式切换样式的应用，css中添加`transition`过渡属性

**解决：**
```html
<input :style="[isFocus ? '' : {width: searchText.length + 3 + 'rem'}]" type="text" v-on="{focus: isFocus = true, blur: isFocus = false}" v-model="searchText">
```
```css
input {
    width: 100%;
    transition: width .1s linear;
}
```
