### ISSUE TITLE
同一页面分为左右两块区域独立滚动，点击左侧导航定位到右侧内容，导航能随着内容滚动激活，并且希望锚点定位不被顶部导航栏遮挡

### ISSUE THREAD

**Issue by shawxlee** [shawxlee/practice-works#16]
**问题：**
同一页面分为左右两块区域独立滚动，点击左侧导航定位到右侧内容，导航能随着内容滚动激活，并且希望锚点定位不被顶部导航栏遮挡

**Comment by shawxlee** [comment]
**分析：**
利用Bootstrap中的[Scrollspy组件](https://getbootstrap.com/docs/4.3/components/scrollspy/)实现滚动监听功能，使导航随着内容滚动激活，注意给关键元素们添加正确的定位，向导航元素添加`overflow-y: auto;`使之也可滚动。
计算顶部导航栏的遮挡高度，设置空锚点，利用`position: relative;`偏移锚点位置，使之定位到顶部时撑开一定高度使内容不被遮挡，并且不会影响视图间距。

**解决：**
```html
<body data-spy="scroll" data-target="#example-nav" data-offset="72">
    <!-- 顶部有固定导航栏，高度为72px -->
    ……
    <!-- 利用网格系统分左右两个区域 -->
    <div class="container">
        <div class="col-4">
            <!-- 导航区域 -->
            <div class="list-group" id="example-nav">
                <a class="list-group-item list-group-item-action" href="#item-1">item-1</a>
                <a class="list-group-item list-group-item-action" href="#item-2">item-2</a>
                ……
            </div>
        </div>
        <div class="col-8">
            <!-- 内容区域 -->
            <div class="example-content">
                <div class="example-content-item-1">
                    <!-- 给每个项目设置空锚点 -->
                    <div class="item-id" id="item-1"></div>
                    <div class="item-1-content">……</div>
                </div>
                <div class="example-content-item-2">
                    <div class="item-id" id="item-2"></div>
                    <div class="item-2-content">……</div>
                </div>
                ……
            </div>
        </div>
    </div>
</body>
```
```css
body {
	position: relative;    /* 给监听对象添加relative定位 */
}
.list-group {
	position: fixed;    /* 给导航元素添加fixed定位 */
	top: 72px;    /* 跨过顶部导航栏 */
	left: 0;
	height: calc(100vh - 72px);    /* 计算可见高度 */
	overflow-y: auto;    /* 添加y轴方向的滚动属性 */
}
.item-id {
	position: relative;    /* 给锚点元素添加relative定位 */
	top: -72px;    /* 上移锚点位置跨过顶部导航栏 */
}
```
