### ISSUE TITLE
安卓系统下，.list-group组件添加position: fixed;定位后，子元素.list-group-item右侧1px的边框看不见了，修改z-index层级也无效

### ISSUE THREAD

**Issue by shawxlee** [shawxlee/practice-works#18]
**问题：**
安卓系统下，`.list-group`组件添加`position: fixed;`定位后，子元素`.list-group-item`右侧1px的边框看不见了，修改`z-index`层级也无效

**Comment by shawxlee** [comment]
**分析：**
暂时未找到发生这个问题的根本原因，不过这里我只需要显示一个右边框出来，所以可以向外层容器添加右边框，同时将子元素的右边框删除或者隐藏，这里为了保留上下边框不能删除，所以采用隐藏的方式

**解决：**
```css
.list-group {
    position: fixed;
    width: 30%;
    overflow-x: hidden;
}
.list-group-item {
    width: calc(100% + 1px);
}
```
