### ISSUE TITLE
内联元素中的文本居中对齐的通用办法

### ISSUE THREAD

**Issue by shawxlee** [shawxlee/practice-works#6]
**问题：**
内联元素中的文本居中对齐的通用办法

**Comment by shawxlee** [comment]
**分析：**
贴一下之前学习CSS时利用[ProcessOn](https://www.processon.com/)自己绘制的行级盒子结构图：

![行级盒子结构分析@shawxlee绘制](https://github.com/shawxlee/study-notes/blob/master/md%E5%9B%BE%E7%89%87/%E8%A1%8C%E7%BA%A7%E7%9B%92%E5%AD%90%E7%BB%93%E6%9E%84%E5%88%86%E6%9E%90@shawxlee%E7%BB%98%E5%88%B6.png?raw=true)

水平居中很简单，一般`text-align: center;`就ok了；麻烦的是垂直居中，根据结构分析，垂直方向上没有精准的中线定义，所以`vertical-align`属性根本无法满足要求，于是最好自行配合调整4个属性：`font-size`、`line-height`、`padding-y`、`height`

**解决：**
```css
/* 当font-size为基准值1rem时，line-height = height即可 */
.inline-el {
    width: 3rem;
    height: 5rem;
    font-size: 1rem;
    line-height: 5;
    text-align: center;
}

/* 当font-size非基准值时，设line-height = 1， paddingTop = paddingBottom = (height - fontSize) / 2 */
.inline-el {
    width: 3rem;
    height: 5rem;
    padding-top: 2.1rem;
    padding-bottom: 2.1rem;
    font-size: .8rem;
    line-height: 1;
    text-align: center;
}
```
