### ISSUE TITLE
问题：内容较多的文本不换行也不溢出，可在行内左右滑动查看

### ISSUE THREAD

**Issue by shawxlee** [shawxlee/practice-works#8]
内容较多的文本不换行也不溢出，可在行内左右滑动查看

**Comment by shawxlee** [comment]
**分析：**
向该文本元素添加CSS属性`white-space: nowrap;`和`overflow-x: auto;`即可，但注意元素必须为块元素或行内块元素，需要设定好宽度

**解决：**
```css
p {
    width: 80%;
    white-space: nowrap;
    overflow-x: auto;
}
```
